### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by Toby222**
Overhaul the API wrapper
Still stuff to do, but I'm not sure what or how, so I'd need help from here

### CODE REVIEW

**Comment by toman222** [comment]
_**Silence, dog**_

**Comment by toman222** [comment]
@supertiger1234 Opinions/comments so far?

**Comment by toman222** [comment]
Still stuff to do, but I'm not sure what or how, so I'd need help from here

**Comment by supertiger1234** [comment]
youre adding a lot of features in a single pull requeets, kinda making me overwhelmed xD

**Comment by toman222** [comment]
It's not really many features, really mostly visual changes ^^;

**Comment by supertiger1234** [comment]
all this hound is annoying. im removing this bot lol

**Comment by toman222** [comment]
Hound doesn't even support TypeScript anyways, lol

**Comment by toman222** [comment]
Squashed the commits to clean up the git history
the per-commit version is still at https://github.com/toman222/nertivia.js/tree/dev

**Pull request closed without merging**
